import { existsSync, readFileSync, writeFileSync } from "fs";
import { join, resolve } from "path";

export const PI_RELOAD_BRIDGE_COMMAND = "pimate-internal-reload";
const PI_RELOAD_BRIDGE_FILE = ".pimate-reload-bridge.js";

const PI_RELOAD_BRIDGE_SOURCE = `// Generated by Pimate. Changes will be replaced when the plugin starts.
export default function pimateReloadBridge(pi) {
  pi.registerCommand("${PI_RELOAD_BRIDGE_COMMAND}", {
    description: "Pimate internal resource reload bridge",
    handler: async (_args, ctx) => {
      if (!ctx.isIdle() || ctx.hasPendingMessages()) {
        throw new Error("Pi must be idle before resources can be reloaded");
      }
      await ctx.reload();
    },
  });
}
`;

/** Materialize the bundled bridge beside the installed plugin bundle. */
export function ensurePiReloadBridge(
  vaultBasePath: string,
  pluginDir: string | undefined
): string {
  if (!pluginDir) throw new Error("Obsidian did not provide the plugin directory");

  const bridgePath = resolve(join(vaultBasePath, pluginDir, PI_RELOAD_BRIDGE_FILE));
  const current = existsSync(bridgePath) ? readFileSync(bridgePath, "utf8") : null;
  if (current !== PI_RELOAD_BRIDGE_SOURCE) {
    writeFileSync(bridgePath, PI_RELOAD_BRIDGE_SOURCE, "utf8");
  }
  return bridgePath;
}
